# Generated by Django 6.0.7 on 2026-07-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_prompt', models.TextField()),
                ('title', models.CharField(max_length=220)),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Thriller', 'Thriller'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Historical', 'Historical'), ('Crime', 'Crime'), ('Superhero', 'Superhero'), ('Cyberpunk', 'Cyberpunk'), ('Steampunk', 'Steampunk'), ('Zombie', 'Zombie'), ('Survival', 'Survival'), ('Magic', 'Magic'), ('Anime', 'Anime')], default='Fantasy', max_length=40)),
                ('theme', models.CharField(blank=True, max_length=60)),
                ('tone', models.CharField(choices=[('Funny', 'Funny'), ('Dark', 'Dark'), ('Serious', 'Serious'), ('Emotional', 'Emotional'), ('Epic', 'Epic'), ('Inspirational', 'Inspirational')], default='Epic', max_length=40)),
                ('audience', models.CharField(choices=[('Kids', 'Kids'), ('Teen', 'Teen'), ('Adult', 'Adult')], default='Teen', max_length=10)),
                ('style', models.CharField(choices=[('Simple', 'Simple'), ('Professional', 'Professional'), ('Poetic', 'Poetic'), ('Novel', 'Novel'), ('Movie Script', 'Movie Script'), ('Comic', 'Comic')], default='Novel', max_length=40)),
                ('length', models.CharField(choices=[('500', '500 words'), ('1000', '1000 words'), ('3000', '3000 words'), ('10000', '10000 words'), ('novel', 'Novel')], default='1000', max_length=10)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('structure_beginning', models.TextField(blank=True)),
                ('structure_conflict', models.TextField(blank=True)),
                ('structure_rising_action', models.TextField(blank=True)),
                ('structure_climax', models.TextField(blank=True)),
                ('structure_ending', models.TextField(blank=True)),
                ('plot_twist', models.TextField(blank=True)),
                ('ending', models.TextField(blank=True)),
                ('cover_seed', models.CharField(blank=True, max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SequelIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequel_ideas', to='stories.story')),
            ],
        ),
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('genre', models.CharField(blank=True, max_length=40)),
                ('tone', models.CharField(blank=True, max_length=40)),
                ('audience', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_history', to=settings.AUTH_USER_MODEL)),
                ('resulting_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stories.story')),
            ],
            options={
                'verbose_name_plural': 'Prompt history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DialogueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('character_name', models.CharField(max_length=120)),
                ('line', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_lines', to='stories.story')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.CharField(blank=True, max_length=40)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('personality', models.CharField(blank=True, max_length=240)),
                ('goal', models.CharField(blank=True, max_length=240)),
                ('weakness', models.CharField(blank=True, max_length=240)),
                ('strength', models.CharField(blank=True, max_length=240)),
                ('skills', models.CharField(blank=True, max_length=240)),
                ('secrets', models.CharField(blank=True, max_length=240)),
                ('backstory', models.TextField(blank=True)),
                ('avatar_seed', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='stories.story')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='stories.story')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Thriller', 'Thriller'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Historical', 'Historical'), ('Crime', 'Crime'), ('Superhero', 'Superhero'), ('Cyberpunk', 'Cyberpunk'), ('Steampunk', 'Steampunk'), ('Zombie', 'Zombie'), ('Survival', 'Survival'), ('Magic', 'Magic'), ('Anime', 'Anime')], default='Fantasy', max_length=40)),
                ('dark_mode', models.BooleanField(default=True)),
                ('font_size', models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='md', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('anthropic_api_key', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorldDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('kingdoms_cities', models.CharField(blank=True, max_length=240)),
                ('magic_or_technology', models.CharField(blank=True, max_length=240)),
                ('climate', models.CharField(blank=True, max_length=160)),
                ('culture', models.CharField(blank=True, max_length=240)),
                ('history', models.TextField(blank=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='world', to='stories.story')),
            ],
        ),
    ]
