# Generated by Django 6.0.7 on 2026-07-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='full_story',
            field=models.TextField(blank=True),
        ),
    ]
